export { fiAppConfig, fiUiColors, fiUiThemeColors } from './app-config'
export { FI_CHROME_COLOR, readRootColor } from './chrome'
export { contrast, mixOklch } from './color'
export { fiConfigKey, useFiConfig } from './composables/useFiConfig'
export type { FiUiConfig } from './composables/useFiConfig'
export { createFiThemeState, fiThemeKey, useFiTheme } from './composables/useFiTheme'
export type { FiThemeState } from './composables/useFiTheme'
export { fiContact, fiLegalNotice, fiPortalUrl, fiPrivacyUrl, fiSocialLinks, fiTopBarSocial, fiTopLinks } from './fi-data'
export type { FiContact, FiLink, FiSocialLink } from './fi-data'
export { FI_TIME_ZONE, fiDefaultCalendar, monthDayIn, resolveFiTheme } from './themes/calendar'
export type { FiCalendarEntry, FiThemeSetting, ResolveFiThemeOptions } from './themes/calendar'
export { FI_DEFAULT_THEME, fiThemeIds, fiThemes, isFiThemeId } from './themes/registry'
export type { FiDateWindow, FiThemeDefinition, FiThemeId, MonthDay } from './themes/registry'

export { default as FiBackButton } from './components/FiBackButton.vue'
export { default as FiFooter } from './components/FiFooter.vue'
export { default as FiHeader } from './components/FiHeader.vue'
export { default as FiLogo } from './components/FiLogo.vue'
export { default as FiReveal } from './components/FiReveal.vue'
export { default as FiSectionHeading } from './components/FiSectionHeading.vue'
export { default as FiStepBadge } from './components/FiStepBadge.vue'
export { default as FiThemeRibbon } from './components/FiThemeRibbon.vue'
export { default as FiTopBar } from './components/FiTopBar.vue'
export { fiLocaleKey, resolveText, useFiLocale, useFiT, useFiText } from './i18n'
export type { FiLocale, FiMessageKey, LocalizedText } from './i18n'
