export { fiAppConfig, fiIcons, fiPrimaryOnTint, fiStatusColors, fiUiColors, fiUiThemeColors } from './app-config'
export { FI_CHROME_COLOR, fiChromeColor, readRootColor } from './chrome'
export { contrast, mixOklch } from './color'
export { fiReadableTextOn, fiStatusIcons } from './composables/fiComponents'
export type { FiIconBadgeSize, FiIconBadgeTone, FiStatItem, FiStatTone, FiStatus } from './composables/fiComponents'
export { fiConfigKey, useFiConfig } from './composables/useFiConfig'
export type { FiUiConfig } from './composables/useFiConfig'
export { createFiThemeState, fiThemeKey, useFiTheme } from './composables/useFiTheme'
export type { FiThemeState } from './composables/useFiTheme'
export { fiContact, fiLegalNotice, fiPortalUrl, fiPrivacyUrl, fiSocialLinks, fiTopBarSocial, fiTopLinks } from './fi-data'
export type { FiContact, FiLink, FiSocialLink } from './fi-data'
export { FI_TIME_ZONE, fiDefaultCalendar, monthDayIn, resolveFiTheme } from './themes/calendar'
export type { FiCalendarEntry, FiThemeSetting, ResolveFiThemeOptions } from './themes/calendar'
export { FI_DEFAULT_THEME, fiThemeIds, fiThemes, isFiThemeId } from './themes/registry'
export type { FiDateWindow, FiThemeDefinition, FiThemeId, MonthDay } from './themes/registry'

export { default as FiBackButton } from './components/FiBackButton.vue'
export { default as FiCtaBand } from './components/FiCtaBand.vue'
export { default as FiDashboardBrand } from './components/FiDashboardBrand.vue'
export { default as FiFooter } from './components/FiFooter.vue'
export { default as FiHeader } from './components/FiHeader.vue'
export { default as FiIconBadge } from './components/FiIconBadge.vue'
export { default as FiLogo } from './components/FiLogo.vue'
export { default as FiPageHeader } from './components/FiPageHeader.vue'
export { default as FiReveal } from './components/FiReveal.vue'
export { default as FiSectionCard } from './components/FiSectionCard.vue'
export { default as FiSectionHeading } from './components/FiSectionHeading.vue'
export { default as FiStat } from './components/FiStat.vue'
export { default as FiStatGrid } from './components/FiStatGrid.vue'
export { default as FiStatusBadge } from './components/FiStatusBadge.vue'
export { default as FiStepBadge } from './components/FiStepBadge.vue'
export { default as FiThemeRibbon } from './components/FiThemeRibbon.vue'
export { default as FiTopBar } from './components/FiTopBar.vue'
export { fiLocaleKey, normalizeFiLocale, resolveText, useFiLocale, useFiT, useFiText } from './i18n'
export type { FiLocale, FiMessageKey, LocalizedText } from './i18n'
